### ISSUE TITLE
Running `delivery init` in the wrong directory leads to a half-configured/broken delivery project and unhelpful error message.

### ISSUE THREAD

**Issue by tonyflint** [chef/delivery-cli#18]
**Environment information**
```
$ chef -v
Chef Development Kit Version: 0.17.17
chef-client version: 12.13.37
delivery version: master (f68e5c5804cd7d8a76c69b926fbb261e1070751b)
berks version: 4.3.5
kitchen version: 1.11.1
```
Delivery server version: `0.5.125`

We use delivery with Github Enterprise for our SCM system. When we accidentally run `delivery init` in the wrong directory, a project is set up in delivery with the name of the directory in which the init was run, but is pointing to the github repo specified in the `delivery init` command.

If you try to fix it by running the same `delivery init` command in the correct directory:
- a standard 500 error is thrown that doesn't contain information specifying what to do;
- One must 'know' that the other project must be deleted, and that the project name is the errant directory in which the command was run, vs. what the user thinks it should be.

**Repro steps**

1. Create a cookbook and initialize it on a Github Enterprise server, e.g.

 ```
 cd /tmp
 chef generate cookbook test_cookbook
 cd test_cookbook
 hub create my_github_org/test_cookbook
 git add .
 git commit -m "Initial commit."
 git push origin master
 ```
2. Create another git repo and accidentally initialize it in delivery pointing at the repo from step 1:

 ``` 
 cd /tmp
 mkdir derp
 cd derp
 git init
 delivery init --repo-name test_cookbook --github my_github_org --server my.delivery-server.com --ent my_delivery_ent --org my_delivery_org --skip-build-cookbook --user $USER
 ```
3. Realize your mistake and try to run the init properly:

 ```
  cd /tmp/test_cookbook
  delivery init --repo-name test_cookbook --github my_github_org --server my.delivery-server.com --ent my_delivery_ent --org my_delivery_org --skip-build-cookbook --user $USER
 ```

**Results**
- An unhelpful error message on the CLI:
```
delivery init --repo-name test_cookbook --github my_github_org --server my.delivery-server.com --ent my_delivery_ent --org my_delivery_org --skip-build-cookbook --user $USER
Chef Delivery
Loading configuration from /tmp/test_cookbook
Creating Github backed Delivery project...
An API Error occured
API request returned 500 Internal Server Error
```

- A somewhat helpful error in the delivery logs:
```
==> /var/log/delivery/delivery/console.log <==
2016-09-06 17:53:54.769 [error] <0.18659.6> failed_call={deliv_db:qfetch, [deliv_project,create_scm_project,[<<"my_delivery_ent">>,<<"my_delivery_org">>,<<"test_cookbook">>,<<"master">>,deliv_scm_github,<<"my_github_org">>,<<"test_cookbook">>]]}; reason={conflict,<<"duplicate key value violates unique constraint \"project_github_metadata_repo_owner_repo_name_key\"">>}
```

In this case, the database is set up with a `project` named `derp`

```
$ /opt/delivery/embedded/bin/psql -U delivery -c 'select * from projects order by id desc limit 1;'
 id  | organization_id |                 guid                 | name |    scm_module
-----+-----------------+--------------------------------------+------+------------------
 268 |               1 | bf17c4d7-759f-4eb0-a74f-15a2a366873b | derp | deliv_scm_github
(1 row)
```

and a project_github_metadata entry for `test_cookbook`
````
$ /opt/delivery/embedded/bin/psql -U delivery -c 'select * from project_github_metadata order by project_id desc limit 1;'
 project_id |  repo_owner  |   repo_name   | token
------------+--------------+---------------+--------
        268 | my_github_org | test_cookbook | unused
(1 row)
```

**Workaround**

One must delete the project, specifying the name of the directory in which the errant delivery command was run:
`delivery api delete orgs/my_delivery_org/projects/derp --server my.delivery-server.com --ent my_delivery_ent --user $USER`

**Ideas for making this better**
- Potentially showing a warning/error if the directory name in which the init command is run doesn't match the repo name?
- Make `delivery init` name the project within delivery whatever the github repo name is?
- Reporting a better error message from the delivery init command, e.g. `ERROR: existing project <name> already pointing at <github repo>`
- Reporting a better error message in the delivery server logs e.g. `ERROR: existing project <name> already pointing at <github repo>` in addition to/instead of the existing one, which assumes at least some knowledge of how the DB schema works with delivery.

**Comment by afiune** [comment]
@tonyflint my good friend! 😄 Thank you so much for creating a nice documented issue. We really appreciate all the feedback y'all have provided to us.

I definitely see the issue that happened here, but just to clarify the current behavior. The delivery-cli does NOT verify the repository name that you are trying to link between GHE and Workflow. The main reason is that Workflow Server allows you to do that; You can link a Project with a different name than the name of the repository in GHE.

Having said that, I agree in the following ideas that you provided:
> Reporting a better error message from the delivery init command, e.g. ERROR: existing project <name> already pointing at <github repo>

**We can definitely do this, although we might have to wait a bit since we are coding the GHEv2 but we might be able to include this new feature on the board.**

>Reporting a better error message in the delivery server logs e.g. ERROR: existing project <name> already pointing at <github repo> in addition to/instead of the existing one, which assumes at least some knowledge of how the DB schema works with delivery.

**This also feels right, I will pass along this new feature as well. 😄**

Do you feel that doing these two things above will solve or mitigate this problem you had? Let us know what are your thoughts... Thanks!

**Comment by sdelano** [comment]
@tonyflint @afiune - thanks for the detailed report!

We're currently working on the next version of Chef Automate and GitHub integration. Currently, we only support creating "new-style" GitHub integrations via the web console, but when the feature is complete you will be able to create integrated projects via the command line in the same way as you've done above.

I've verified as well that the repo creation API for new-style GitHub projects does indeed return a 409 Conflict with a helpful error message when trying to link to a GitHub repo that has already been linked to.

When this feature is complete, all GitHub-integrated projects will be migrated to the new style and this feature will make it into the core API. Because of this, we'll not be fixing up the existing API. The new API is scheduled to be released within a few weeks.

Thanks!

@afiune - I'll leave this ticket open if you'd like to address any of the cli-only issues like directory name warning or enforcing project + repo naming conventions.

**Comment by afiune** [comment]
@tonyflint I would like to ask you for some feedback. 😄 

If when you run the `delivery init` command it display something like this:
```
➜  my_A_project git:(master) delivery init --github org --repo-name my_B_project
Chef Delivery
Loading configuration from /Users/salimafiune/chef/delivery/organizations/sandbox/my_A_project
WARN: The directory you are located does't match with the repository name you are trying to initialize.
Press Enter to continue or Ctr+C to abort.^C
```

Where if you press **Enter** it will continue, but if you don't you have to exit with **Ctrl+C**. 

_Would you consider this as a good solution for the directory problems you mentioned above?_

I am open to suggestions! Thanks!! 🎉

**Comment by tonyflint** [comment]
@afiune Thanks for asking!!

In my view, the error message should state _what_ the impact will be or what might go wrong. For example, I think in your example, running `delivery init --github org --repo-name my_B_project` within a folder named `my_A_project`, the project within the delivery UI would be called `my_A_project` which might lead to confusion for people wondering what repo with which it is associated.

Maybe just a message saying something like "The project within the Automate UI will be named `my_A_project` -- please confirm that this is what you want.".

**Comment by afiune** [comment]
That sounds reasonable.. So @tonyflint something like this? 😺 
```
➜  my_A_project git:(master) delivery init --github org --repo-name my_B_project
Chef Delivery
Loading configuration from /Users/salimafiune/chef/delivery/organizations/sandbox/my_A_project
WARN: The project within the Automate UI will be named my_A_project.
Press Enter to confirm that this is what you want or Ctr+C to abort.^C
```

**Comment by tonyflint** [comment]
👍 👍 👍 👍 👍 👍 👍 👍 👍

**Comment by afiune** [comment]
Change had some feedback from the Team. 

**The final message will be the following:**

If the answer is **"n"**
```
➜  project_A git:(maste) delivery init --github org --repo-name project_B
Chef Delivery
Loading configuration from /Users/salimafiune/chef/delivery/organizations/sandbox/project_A
WARN: This project will be named 'project_A', but the repository name is 'project_B'.
Are you sure this is what you want? y/n: n
Project and repository name mismatch.

To match the project and the repository name you can:
  1) Create a directory with the same name as the repository.
  2) Clone or download the content of the repository inside.
  3) Run the 'delivery init' command within the new directory.
```

If the answer is **"y"** it will continue with the project initialization.
