### ISSUE TITLE
Delivery init with --local flag creates a build cookbook and config

### ISSUE THREAD

**Issue by tas50** [chef/delivery-cli#23]
When doing a delivery init with the local flag you still get a lot of Delivery the product sort of files. It seems like it would be really helpful to handle this different so we could push adoption of delivery CLI as a local workflow tool which leads into use of Automate.

**Comment by afiune** [comment]
@tas50 So you have indeed tried `--local` 🤔  I see where is this coming from, as the init command is very specific for the project initialization in Automate, I would like to know what are you trying to achieve so I can recommend something or fix if needed be.

For skipping the build-cookbook/config you can use the flag `--skip-build-cookbook` but if you do not have a `.delivery/config.json` it might not let you continue since this is a MUST have from the initialization point of view.

Another option is to use a custom generator, this could create a custom `config.json` and do more stuff that you require on the initialization of your project.

Let me know if you want to chat over zoom so I understand more what are you trying to do. ✌

**Comment by afiune** [comment]
If the comment didn't clarify things, I'll happy to re-open.
