### ISSUE TITLE
delivery review claims to fail to push branch to BitBucket repo

### ISSUE THREAD

**Issue by mattlqx** [chef/delivery-cli#30]
What is actually happening here?

```
Chef Delivery
Loading configuration from /Users/matt/src/myproject
Review for change mybranch targeted for pipeline master
Created new patchset        
Failed to push branch to Bitbucket: fatal: remote error: Repository not found        
The requested repository does not exist, or you do not have permission to        
access it. 
(url)
```

The branch exists on both origin and delivery, I can manipulate them just fine with git. Which is failing to push? Not being able to put delivery into a debug output mode is rather frustrating.

The updated changeset does appear on the Chef Automate server despite whatever supposedly failing push.

**Comment by mattlqx** [comment]
I figured this out. It looks like that part is to create a pull request on the repo, which of course, the user account you setup in the Chef Automate console for the SCM config is who needs write permissions on the repo in order to do. Added Chef user to my repos with the write permission and, voila, it creates and links a new pull request.

A more succinct error message would've been helpful though!

**Comment by afiune** [comment]
Hi @mattlqx - Glad to hear you got this figured out. I wanna point out that we do have some documentation related to this issue: https://docs.chef.io/integrate_delivery_bitbucket.html#create-a-project 

In there you will find the requirements to create a project linked with bitbucket. Even though we could improve improve our error message on the CLI, I'll take a note to do so. 

Im closing this since it is not a current issue, please reach out if you need this to be re-open.

Thank you for your feedback!
