### ISSUE TITLE
Error's during omnibus build delivery-cli

### ISSUE THREAD

**Issue by siddheshwar-more** [chef/delivery-cli#5]
We are getting some errors during omnibus build https://github.com/chef/delivery-cli/tree/master/omnibus-delivery-cli#build 
$ bin/omnibus build delivery-cli 

Refer this gist for logs-  https://gist.github.com/siddheshwar-more/7ad40bc0816fb51492b3 

Note- we are using current master branch .

Could you please help us to resolve this build issue.

Thank you!

**Comment by siddheshwar-more** [comment]
@chef-delivery ^

**Comment by christophermaier** [comment]
@siddheshwar-more It looks like your Rust is a bit behind. I'd try running `make rustup` from the root directory first, then doing your omnibus build.

It looks like this is happening because Rust itself isn't actually part of the omnibus build itself. I think this is because a) Rust isn't a runtime dependency of the CLI and b) it looks like it is assuming it's running on a Delivery builder, which will have Rust installed already prior to building. That's a bit confusing in this case, unfortunately; I'll file an issue to make this more robust.

**Comment by christophermaier** [comment]
@siddheshwar-more Did that help?

**Comment by siddheshwar-more** [comment]
@christophermaier 
`make rustup` is helped !

Thank you!

**Comment by christophermaier** [comment]
@siddheshwar-more Good to hear!

Closing as resolved.
